version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.21
    ports:
      - 8081:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
    restart: always
    depends_on:
      - app
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    restart: always
    tty: true
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./db/Dockerfile
    # volumes:
      # - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウント
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
    restart: always
    command: mysqld
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      - ./public:/public
    tty: true
