version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - 8081:80
    tty: true
    depends_on:
      - app
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    tty: true
